### ISSUE TITLE
Need to handle Elimination matches

### ISSUE THREAD

**Issue by JacobAMason** [JacobAMason/Velocity-Vortex-Scorekeeper-Server#3]
There are two ways to approach this issue:
1. Elimination matches can be read in from a new matches.txt file or from the alliances.txt file after match generation. Either approach is acceptable, but alliances.txt might be the better file to read in so the elimination matches can be handled separately from the qualification matches.
2. Elimination alliances can be created on the scorekeeper screen by implementing alliance generation inside the scorekeeper client.

AC:
- [ ] There should be a new section on the scorekeeper page for elimination matches. A good approach would be to separate the qualification and elimination matches into switch-able panels so that the scorekeeper can change the view to see the elimination matches.
- [ ] On the elimination screen, the matches should be configurable and selectable.
- [ ] Must have support for three team alliances

**Comment by emmell620** [comment]
Maybe should read all 3 teams per alliance in matches.txt. And if a team number is 0, then not display it.  Then when the eliminations are generated, you can read matches.txt and display all 3 teams in the audience display (like the match preview screen on the regular scoring software).

**Comment by JacobAMason** [comment]
Instead of doing any of the above, @mdttrump97 and I just made a custom field to enter in any team numbers to the display #4.
